import type {
  AdminReview,
  Badge,
  CareGuideStep,
  CareReminder,
  Challenge,
  CommunityStanding,
  ProofSubmission,
  Tree,
  TreeCoinLedger,
  User,
} from "./types";
import { GROWCRED_ASSETS } from "./assets";

const treeProofVisuals = {
  mango: GROWCRED_ASSETS.treeThumbnails.mango,
  neem: GROWCRED_ASSETS.treeThumbnails.neem,
  gulmohar: GROWCRED_ASSETS.treeThumbnails.gulmohar,
  peepal: GROWCRED_ASSETS.treeThumbnails.peepal,
  jamun: GROWCRED_ASSETS.treeThumbnails.jamun,
  tamarind: GROWCRED_ASSETS.treeThumbnails.tamarind,
  indianAlmond: GROWCRED_ASSETS.treeThumbnails.indianAlmond,
  banyan: GROWCRED_ASSETS.treeThumbnails.banyan,
} as const;

export const users: User[] = [
  {
    id: "user-1",
    name: "Aarav Mehta",
    email: "aarav@growcred.test",
    avatarUrl: "AM",
    city: "Delhi",
    country: "India",
    totalTreeCoins: 140,
    verifiedTrees: 3,
    badges: ["badge-1", "badge-2"],
    createdAt: "2026-01-12",
  },
  {
    id: "user-2",
    name: "Maya Rao",
    email: "maya@growcred.test",
    avatarUrl: "MR",
    city: "Bengaluru",
    country: "India",
    totalTreeCoins: 220,
    verifiedTrees: 7,
    badges: ["badge-1", "badge-2", "badge-3"],
    createdAt: "2026-01-25",
  },
  {
    id: "user-3",
    name: "Kabir Singh",
    email: "kabir@growcred.test",
    avatarUrl: "KS",
    city: "Pune",
    country: "India",
    totalTreeCoins: 95,
    verifiedTrees: 2,
    badges: ["badge-1"],
    createdAt: "2026-02-08",
  },
  {
    id: "user-4",
    name: "Ira Nair",
    email: "ira@growcred.test",
    avatarUrl: "IN",
    city: "Kochi",
    country: "India",
    totalTreeCoins: 510,
    verifiedTrees: 18,
    badges: ["badge-1", "badge-2", "badge-3", "badge-4"],
    createdAt: "2026-02-18",
  },
  {
    id: "user-5",
    name: "Zoya Khan",
    email: "zoya@growcred.test",
    avatarUrl: "ZK",
    city: "Mumbai",
    country: "India",
    totalTreeCoins: 310,
    verifiedTrees: 11,
    badges: ["badge-1", "badge-2", "badge-3"],
    createdAt: "2026-03-01",
  },
  {
    id: "user-6",
    name: "Vihaan Das",
    email: "vihaan@growcred.test",
    avatarUrl: "VD",
    city: "Kolkata",
    country: "India",
    totalTreeCoins: 70,
    verifiedTrees: 1,
    badges: ["badge-1"],
    createdAt: "2026-03-11",
  },
];

export const badges: Badge[] = [
  {
    id: "badge-1",
    name: "Seed Starter",
    description: "First verified tree.",
    icon: "seedling",
    requirement: "Verify 1 tree",
  },
  {
    id: "badge-2",
    name: "Green Friend",
    description: "Five verified trees cared for.",
    icon: "leaf",
    requirement: "Verify 5 trees",
  },
  {
    id: "badge-3",
    name: "Tree Hero",
    description: "Ten verified trees with active care.",
    icon: "shield",
    requirement: "Verify 10 trees",
  },
  {
    id: "badge-4",
    name: "Planet Protector",
    description: "Fifty verified trees across care stages.",
    icon: "planet",
    requirement: "Verify 50 trees",
  },
  {
    id: "badge-5",
    name: "Forest Maker",
    description: "One hundred verified trees.",
    icon: "forest",
    requirement: "Verify 100 trees",
  },
  {
    id: "badge-6",
    name: "Proof Pro",
    description: "Reliable proof uploads with clean evidence.",
    icon: "camera",
    requirement: "Submit 10 complete proofs",
  },
];

export const trees: Tree[] = [
  {
    id: "tree-1",
    userId: "user-1",
    nickname: "Nimmy",
    species: "Neem",
    locationName: "South Delhi community lane",
    latitude: 28.5355,
    longitude: 77.2401,
    plantedAt: "2026-04-20",
    status: "verified",
    photos: [treeProofVisuals.neem],
    treeCoinsEarned: 70,
    nextCareReminder: "Water your neem tree tomorrow",
    survivalStage: "90_day",
  },
  {
    id: "tree-2",
    userId: "user-1",
    nickname: "Peepal Pal",
    species: "Peepal",
    locationName: "School garden, Delhi",
    plantedAt: "2026-05-02",
    status: "under_review",
    photos: [treeProofVisuals.peepal],
    treeCoinsEarned: 10,
    nextCareReminder: "Upload a 30-day care check-in",
    survivalStage: "new",
  },
  {
    id: "tree-3",
    userId: "user-2",
    nickname: "Rain Buddy",
    species: "Jamun",
    locationName: "Indiranagar, Bengaluru",
    plantedAt: "2026-02-12",
    status: "verified",
    photos: [treeProofVisuals.jamun],
    treeCoinsEarned: 110,
    nextCareReminder: "Check mulch after weekend rain",
    survivalStage: "180_day",
  },
  {
    id: "tree-4",
    userId: "user-3",
    nickname: "Tiny Tamarind",
    species: "Tamarind",
    locationName: "Baner, Pune",
    plantedAt: "2026-05-13",
    status: "needs_more_info",
    photos: [treeProofVisuals.tamarind],
    treeCoinsEarned: 0,
    nextCareReminder: "Add clearer location proof",
    survivalStage: "new",
  },
  {
    id: "tree-5",
    userId: "user-4",
    nickname: "Coast Guard",
    species: "Indian Almond",
    locationName: "Fort Kochi lane",
    plantedAt: "2026-01-28",
    status: "verified",
    photos: [treeProofVisuals.indianAlmond],
    treeCoinsEarned: 140,
    nextCareReminder: "Trim grass around the base",
    survivalStage: "one_year",
  },
  {
    id: "tree-6",
    userId: "user-5",
    nickname: "Mango Mood",
    species: "Mango",
    locationName: "Dadar society garden",
    plantedAt: "2026-03-19",
    status: "submitted",
    photos: [treeProofVisuals.mango],
    treeCoinsEarned: 10,
    nextCareReminder: "Await verification",
    survivalStage: "30_day",
  },
  {
    id: "tree-7",
    userId: "user-6",
    nickname: "Banyan Baby",
    species: "Banyan",
    locationName: "Salt Lake, Kolkata",
    plantedAt: "2026-06-01",
    status: "draft",
    photos: [treeProofVisuals.banyan],
    treeCoinsEarned: 0,
    nextCareReminder: "Finish proof upload",
    survivalStage: "new",
  },
  {
    id: "tree-8",
    userId: "user-2",
    nickname: "Gulmohar Glow",
    species: "Gulmohar",
    locationName: "College eco club plot",
    plantedAt: "2026-04-02",
    status: "verified",
    photos: [treeProofVisuals.gulmohar],
    treeCoinsEarned: 50,
    nextCareReminder: "90-day proof due this week",
    survivalStage: "90_day",
  },
];

export const challenges: Challenge[] = [
  {
    id: "challenge-1",
    title: "Birthday Tree Challenge",
    description: "Plant or adopt a tree on your birthday and make the day count.",
    reward: 25,
    participants: 1240,
    startDate: "2026-06-01",
    endDate: "2026-12-31",
    status: "open",
    category: "solo",
    proofNeeded: "Birthday planting/adoption proof plus care commitment",
    progress: 72,
    teamType: "Solo mission",
  },
  {
    id: "challenge-2",
    title: "One Student, One Tree",
    description: "A campus mission for every student to verify one tree.",
    reward: 20,
    participants: 3100,
    startDate: "2026-06-10",
    endDate: "2026-09-15",
    status: "open",
    category: "school",
    proofNeeded: "Student proof, school location, and native tree confirmation",
    progress: 58,
    teamType: "School teams",
  },
  {
    id: "challenge-3",
    title: "10 Friends Green Challenge",
    description: "Bring your group, plant together, and track survival together.",
    reward: 40,
    participants: 870,
    startDate: "2026-06-15",
    endDate: "2026-08-30",
    status: "open",
    category: "friends",
    proofNeeded: "Group planting proof with each tree submitted separately",
    progress: 44,
    teamType: "Friend groups",
  },
  {
    id: "challenge-4",
    title: "Weekend Grow Mission",
    description: "Use one weekend to submit clean proof and a care plan.",
    reward: 15,
    participants: 540,
    startDate: "2026-06-20",
    endDate: "2026-07-31",
    status: "closing",
    category: "city",
    proofNeeded: "Weekend proof bundle with location and care plan",
    progress: 86,
    teamType: "City squads",
  },
  {
    id: "challenge-5",
    title: "Campus Green Battle",
    description: "Schools and colleges compete on verified survival, not promises.",
    reward: 60,
    participants: 2230,
    startDate: "2026-07-01",
    endDate: "2026-10-01",
    status: "open",
    category: "campus",
    proofNeeded: "Campus team submissions ranked by verified survival",
    progress: 39,
    teamType: "Campus teams",
  },
];

export const schoolStandings: CommunityStanding[] = [
  {
    id: "school-1",
    name: "Green Valley Public School",
    location: "Delhi",
    verifiedTrees: 342,
    treeCoinsEarned: 11280,
    badges: ["Campus Green Battle", "Proof Pro"],
    rankLabel: "Top School",
  },
  {
    id: "school-2",
    name: "NPS Eco Club",
    location: "Bengaluru",
    verifiedTrees: 298,
    treeCoinsEarned: 9840,
    badges: ["One Student, One Tree"],
    rankLabel: "Fastest Climber",
  },
  {
    id: "school-3",
    name: "St. Mira Green Team",
    location: "Pune",
    verifiedTrees: 231,
    treeCoinsEarned: 7710,
    badges: ["Care Streak"],
    rankLabel: "Care Leader",
  },
  {
    id: "school-4",
    name: "Kochi Youth Nature Club",
    location: "Kochi",
    verifiedTrees: 204,
    treeCoinsEarned: 6920,
    badges: ["Survival Squad"],
    rankLabel: "Coastal Crew",
  },
];

export const cityStandings: CommunityStanding[] = [
  {
    id: "city-1",
    name: "Bengaluru",
    location: "Karnataka",
    verifiedTrees: 1280,
    treeCoinsEarned: 42100,
    badges: ["Top City", "Campus Energy"],
    rankLabel: "Most Active",
  },
  {
    id: "city-2",
    name: "Delhi",
    location: "NCR",
    verifiedTrees: 1110,
    treeCoinsEarned: 38240,
    badges: ["School Teams"],
    rankLabel: "Proof Leader",
  },
  {
    id: "city-3",
    name: "Mumbai",
    location: "Maharashtra",
    verifiedTrees: 940,
    treeCoinsEarned: 31800,
    badges: ["Weekend Grow"],
    rankLabel: "Challenge Hub",
  },
  {
    id: "city-4",
    name: "Kochi",
    location: "Kerala",
    verifiedTrees: 812,
    treeCoinsEarned: 27600,
    badges: ["Survival Focus"],
    rankLabel: "Care Quality",
  },
];

export const challengeStandings: CommunityStanding[] = challenges.map(
  (challenge, index) => ({
    id: `${challenge.id}-standing`,
    name: challenge.title,
    location: challenge.teamType,
    verifiedTrees: Math.round(challenge.participants * (challenge.progress / 100) * 0.42),
    treeCoinsEarned: challenge.participants * challenge.reward,
    badges: [challenge.status === "closing" ? "Closing Soon" : "Open Mission"],
    rankLabel: `#${index + 1} Mission`,
  }),
);

export const careGuideSteps: CareGuideStep[] = [
  {
    id: "care-1",
    dayRange: "Day 0",
    title: "Plant with permission",
    description: "Choose a legal, safe spot with enough room for roots, canopy, and future care.",
    actions: [
      "Confirm permission before digging",
      "Pick a native or locally suitable species",
      "Photograph the location before and after planting",
    ],
    proofTip: "Capture the sapling, surrounding context, and planting date in one clear proof set.",
  },
  {
    id: "care-2",
    dayRange: "Days 1-7",
    title: "Stabilize the sapling",
    description: "The first week is about water, shade balance, and making sure the sapling is not disturbed.",
    actions: [
      "Water deeply, not just on the surface",
      "Keep the base clear of plastic and trash",
      "Check that the sapling stands upright",
    ],
    proofTip: "A short check-in photo should show soil moisture and the full sapling.",
  },
  {
    id: "care-3",
    dayRange: "Days 8-30",
    title: "Build the care rhythm",
    description: "A regular care habit matters more than a dramatic one-time planting moment.",
    actions: [
      "Water based on weather and soil dryness",
      "Add mulch without covering the stem",
      "Protect from animals, foot traffic, and accidental damage",
    ],
    proofTip: "Your 30-day proof should show healthy leaves and the same location context.",
  },
  {
    id: "care-4",
    dayRange: "Days 31-90",
    title: "Prove survival",
    description: "Survival proof should show that the tree is adapting and still being cared for.",
    actions: [
      "Look for new leaves or stable growth",
      "Remove weeds competing around the base",
      "Report damage early instead of hiding it",
    ],
    proofTip: "The 90-day update should make it easy for an admin to compare against older proof.",
  },
  {
    id: "care-5",
    dayRange: "180 days+",
    title: "Keep protecting it",
    description: "Long-term care turns a sapling into verified impact and unlocks stronger rewards.",
    actions: [
      "Schedule seasonal watering checks",
      "Refresh guards or support only when needed",
      "Keep documenting survival milestones",
    ],
    proofTip: "Long-term proof should show tree health, surroundings, and continued access for care.",
  },
];

export const careReminders: CareReminder[] = [
  {
    id: "reminder-1",
    userId: "user-1",
    treeId: "tree-1",
    treeNickname: "Nimmy",
    message: "Water your neem tree tomorrow and upload a quick care check.",
    dueAt: "2026-06-23T09:00:00.000Z",
    channel: "in_app",
    status: "scheduled",
  },
  {
    id: "reminder-2",
    userId: "user-1",
    treeId: "tree-2",
    treeNickname: "Peepal Pal",
    message: "Your 30-day care proof is coming up. Capture leaves and location.",
    dueAt: "2026-06-26T09:00:00.000Z",
    channel: "email",
    status: "scheduled",
  },
  {
    id: "reminder-3",
    userId: "user-2",
    treeId: "tree-8",
    treeNickname: "Gulmohar Glow",
    message: "90-day survival proof is due this week.",
    dueAt: "2026-06-24T09:00:00.000Z",
    channel: "in_app",
    status: "scheduled",
  },
];

export const proofSubmissions: ProofSubmission[] = [
  {
    id: "proof-1",
    treeId: "tree-1",
    userId: "user-1",
    type: "survival_update",
    photoUrl: treeProofVisuals.neem,
    notes: "90-day care check-in with visible new leaves.",
    status: "verified",
    submittedAt: "2026-06-10",
    reviewedAt: "2026-06-11",
    reviewerId: "admin-1",
  },
  {
    id: "proof-2",
    treeId: "tree-2",
    userId: "user-1",
    type: "planting",
    photoUrl: treeProofVisuals.peepal,
    notes: "New peepal planting with school permission.",
    status: "under_review",
    submittedAt: "2026-06-19",
  },
  {
    id: "proof-3",
    treeId: "tree-4",
    userId: "user-3",
    type: "planting",
    photoUrl: treeProofVisuals.tamarind,
    notes: "Photo is clear, location needs confirmation.",
    status: "needs_more_info",
    submittedAt: "2026-06-15",
    reviewedAt: "2026-06-16",
    reviewerId: "admin-1",
  },
  {
    id: "proof-4",
    treeId: "tree-5",
    userId: "user-4",
    type: "care_checkin",
    photoUrl: treeProofVisuals.indianAlmond,
    notes: "Healthy one-year care proof.",
    status: "verified",
    submittedAt: "2026-06-08",
    reviewedAt: "2026-06-09",
    reviewerId: "admin-2",
  },
  {
    id: "proof-5",
    treeId: "tree-6",
    userId: "user-5",
    type: "care_checkin",
    photoUrl: treeProofVisuals.mango,
    notes: "30-day care proof for mango sapling.",
    status: "submitted",
    submittedAt: "2026-06-21",
  },
  {
    id: "proof-6",
    treeId: "tree-7",
    userId: "user-6",
    type: "planting",
    photoUrl: treeProofVisuals.banyan,
    notes: "Draft proof missing consent checks.",
    status: "draft",
    submittedAt: "2026-06-22",
  },
];

export const treeCoinLedger: TreeCoinLedger[] = [
  {
    id: "ledger-1",
    userId: "user-1",
    treeId: "tree-1",
    action: "Verified planting proof",
    amount: 10,
    status: "verified",
    createdAt: "2026-04-21",
  },
  {
    id: "ledger-2",
    userId: "user-1",
    treeId: "tree-1",
    action: "30-day care check-in",
    amount: 10,
    status: "verified",
    createdAt: "2026-05-20",
  },
  {
    id: "ledger-3",
    userId: "user-1",
    treeId: "tree-1",
    action: "90-day survival proof",
    amount: 20,
    status: "verified",
    createdAt: "2026-06-10",
  },
  {
    id: "ledger-4",
    userId: "user-2",
    treeId: "tree-3",
    action: "180-day survival proof",
    amount: 30,
    status: "verified",
    createdAt: "2026-06-02",
  },
  {
    id: "ledger-5",
    userId: "user-2",
    treeId: "tree-8",
    action: "Verified planting proof",
    amount: 10,
    status: "verified",
    createdAt: "2026-04-03",
  },
  {
    id: "ledger-6",
    userId: "user-4",
    treeId: "tree-5",
    action: "1-year survival proof",
    amount: 50,
    status: "verified",
    createdAt: "2026-06-09",
  },
  {
    id: "ledger-7",
    userId: "user-5",
    treeId: "tree-6",
    action: "30-day care check-in",
    amount: 10,
    status: "submitted",
    createdAt: "2026-06-21",
  },
  {
    id: "ledger-8",
    userId: "user-3",
    treeId: "tree-4",
    action: "Verified planting proof",
    amount: 10,
    status: "needs_more_info",
    createdAt: "2026-06-16",
  },
  {
    id: "ledger-9",
    userId: "user-6",
    treeId: "tree-7",
    action: "Draft planting proof",
    amount: 0,
    status: "draft",
    createdAt: "2026-06-22",
  },
  {
    id: "ledger-10",
    userId: "user-4",
    treeId: "tree-5",
    action: "Care streak bonus",
    amount: 20,
    status: "verified",
    createdAt: "2026-06-18",
  },
];

export const adminReviews: AdminReview[] = [
  {
    id: "review-1",
    proofSubmissionId: "proof-1",
    reviewerId: "admin-1",
    decision: "verified",
    notes: "Clear photo, timeline and location match previous proof.",
    fraudFlags: [],
    reviewedAt: "2026-06-11",
  },
  {
    id: "review-2",
    proofSubmissionId: "proof-2",
    reviewerId: "admin-1",
    decision: "under_review",
    notes: "Needs manual species and date check.",
    fraudFlags: ["New account", "Nearby duplicate location"],
  },
  {
    id: "review-3",
    proofSubmissionId: "proof-3",
    reviewerId: "admin-1",
    decision: "needs_more_info",
    notes: "Ask for a wider photo showing location context.",
    fraudFlags: ["Location unclear"],
    reviewedAt: "2026-06-16",
  },
  {
    id: "review-4",
    proofSubmissionId: "proof-4",
    reviewerId: "admin-2",
    decision: "verified",
    notes: "Healthy tree, visible long-term care.",
    fraudFlags: [],
    reviewedAt: "2026-06-09",
  },
  {
    id: "review-5",
    proofSubmissionId: "proof-5",
    reviewerId: "admin-2",
    decision: "submitted",
    notes: "Queue item awaiting first review.",
    fraudFlags: [],
  },
  {
    id: "review-6",
    proofSubmissionId: "proof-6",
    reviewerId: "admin-1",
    decision: "draft",
    notes: "Draft proof cannot be reviewed until consent is complete.",
    fraudFlags: ["Missing consent"],
  },
];
